stages: 
  - build_dev
  - build_master
cache:
  paths:
    - node_modules

steps-dev: 
  stage: build_dev
  script:
    - yarn && yarn build
    - scp -r dist/* 192.168.10.22:/hsh_production/Natural_Ying_Web
    - echo "Dev Publish Complete!"		
  only:
    - dev

steps-master: 
  stage: build_master
  script:
    - yarn && yarn build
    - scp -r dist/* 192.168.6.130:/hsh_production/Natural_Ying_Web
    - echo "Master Publish Complete!"	
  only:
    - master